apiVersion: v1
kind: Service
metadata:
  name: atlantis-actions
  labels:
    app: atlantis-actions
spec:
  selector:
    app: atlantis-actions
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: ClusterIP
