runnerToken:
  valueFrom:
    secretKeyRef:
      name: gitea-runner-token
      key: token

serverURL: "https://git.athq.de"
replicaCount: 3
ephemeral: true

config:
  container:
    runtime: kubernetes
