enabled: true
existingSecret: gitea-runner-token
existingSecretKey: token
init:
  image:
    repository: alpine
    tag: latest
giteaRootURL: "https://git.athq.de"
actRunner:
  container:
    privileged: true
  config: |
    log:
      level: debug
    cache:
      enabled: false
    container:
      valid_volumes:
        - /var/run/docker.sock
      options: -v /var/run/docker.sock:/var/run/docker.sock
runner:
  log:
    level: debug
  cache:
    enabled: false
  container:
    privileged: true
    valid_volumes:
      - /var/run/docker.sock
    options: -v /var/run/docker.sock:/var/run/docker.sock
statefulset:
  replicas: 1

config:
  container:
    runtime: docker

securityContext:
  privileged: true
