apiVersion: v1
kind: Service
metadata:
  name: ax-films
  labels:
    app: ax-films
spec:
  selector:
    app: ax-films
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
