apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: hello-world
  namespace: kathi
spec:
  ingressClassName: traefik
  rules:
    - host: kathi.rancher.katzencluster.atlantishq.de
      http:
        paths:
          - backend:
              service:
                name: hello-world-kathi
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - kathi.rancher.katzencluster.atlantishq.de
      secretName: hello-world-tls
