{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ name }}
  labels:
    app: {{ name }}
spec:
  selector:
    app: {{ name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ svc.targetPort }}
  type: ClusterIP
{{ end }}
