apiVersion: v1
kind: ConfigMap
metadata:
  name: faf-metrics-config
data:
  env.js: |
    // no data
  user_mappings.yaml: |
    sheppy: Sheppy
    stryder: Strydxr
    sheppy-unpriv: Sheppy
    kathi: bekama
    banana: BananaSmoothie
    morax: Morax
    alex: uney

    michy: iTrash
    preisi: preisi
    amelie: mellywalnut
    timo: DadoSpeedy
