apiVersion: apps/v1
kind: Deployment
metadata:
  name: faf-metrics
  labels:
    app: faf-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faf-metrics
  template:
    metadata:
      labels:
        app: faf-metrics
    spec:
      containers:
        - name: faf-metrics-speech
          image: harbor-registry.atlantishq.de/atlantishq/faf-metrics-speech:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          args:
            - server 
            - "-m" 
            - en_US-lessac-high
        - name: faf-metrics-frontend
          image: harbor-registry.atlantishq.de/atlantishq/faf-metrics-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
        - name: faf-metrics-server
          image: harbor-registry.atlantishq.de/atlantishq/faf-metrics-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: cache
              mountPath: /app/static/cache
          env:
            - name: TOKEN
              value: "secret"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: faf-metrics-k3s-db-secret
                  key: db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: faf-metrics-k3s-db-secret
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: faf-metrics-k3s-db-secret
                  key: password
            - name: DB_HOST
              value: "135.181.80.154"
            - name: DB_PORT
              value: "5432"
      volumes:
        - name: cache
          emptyDir: {}
      restartPolicy: Always
