apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fa-metrics
  labels:
    app: fa-metrics
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/redirect-entry-point: "https"
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    traefik.ingress.kubernetes.io/router.middlewares: >
      oauth2-forward-auth-fa-metrics@kubernetescrd,
      fa-metrics-speech-strip@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - fa-metrics.rancher.katzencluster.atlantishq.de
      secretName: fa-metrics-tls
  rules:
    - host: fa-metrics.rancher.katzencluster.atlantishq.de
      http:
        paths:

          - path: /speech
            pathType: Prefix
            backend:
              service:
                name: fa-metrics-speech
                port:
                  number: 5000

          - path: /api
            pathType: Prefix
            backend:
              service:
                name: fa-metrics-server
                port:
                  number: 8080

          # Frontend catch-all
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fa-metrics-frontend
                port:
                  number: 80

