apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlantis-hub
  labels:
    app: atlantis-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlantis-hub
  template:
    metadata:
      labels:
        app: atlantis-hub
    spec:
      containers:
        - name: atlantis-hub
          image: harbor-registry.atlantishq.de/atlantishq/atlantis-hub:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
            - name: icons
              mountPath: /app/static/icons
            - name: cache
              mountPath: /app/static/cache
          env:
            - name: TZ
              value: "UTC"
      volumes:
        - name: config
          configMap:
            name: atlantis-hub-config
            items:
              - key: config.yaml
                path: config.yaml
        - name: icons
          emptyDir: {}
        - name: cache
          emptyDir: {}
      restartPolicy: Always
