apiVersion: v1
kind: Service
metadata:
  name: atlantis-hub
  labels:
    app: atlantis-hub
spec:
  selector:
    app: atlantis-hub
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: ClusterIP
