apiVersion: apps/v1
kind: Deployment
metadata:
  name: yamtrack
  labels:
    app: yamtrack
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: yamtrack
  template:
    metadata:
      annotations:
        version/latest: "A"
      labels:
        app: yamtrack
    spec:
      containers:
        - name: redis
          image: redis:8-alpine
          imagePullPolicy: Always
          volumeMounts:
            - name: redis-data
              mountPath: /data
        - name: yamtrack
          image: ghcr.io/fuzzygrim/yamtrack
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
          env:
            - name: TZ
              value: Europe/Berlin
            - name: URLS
              value: https://paula.atlantishq.de
            - name: REGISTRATION
              value: "true"
            - name: SOCIALACCOUNT_ONLY
              value: "true"
            - name: REDIRECT_LOGIN_TO_SSO
              value: "true"
            - name: SOCIALACCOUNT_PROVIDERS
              valueFrom: 
                secretKeyRef:
                    name: yamtrack-oidc-config
                    key: django-config
            - name: SOCIAL_PROVIDERS
              value: allauth.socialaccount.providers.openid_connect
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yamtrack-secret
                  key: secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: yamtrack-k3s-db-secret
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yamtrack-k3s-db-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: yamtrack-k3s-db-secret
                  key: db
            - name: DB_SSL_MODE
              value: require
            - name: DB_SSL_CERT_MODE
              value: disable
            - name: DB_HOST
              value: "135.181.80.154"
            - name: DB_PORT
              value: "5432"
      volumes:
        - name: redis-data
          emptyDir: {}
      restartPolicy: Always
